//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeGocNho_63134417.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUCVU_QUYEN
    {
        public int id { get; set; }
        public string MACV { get; set; }
        public string MAQUYEN { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual QUYEN QUYEN { get; set; }
    }
}
